version: '3'

services:
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379"
    
  node:
    build: 
      context: ..
      dockerfile: ./docker/node/Dockerfile
    depends_on:
      - redis
    volumes:
      - ..:/usr/src/app
    ports:
      - "8080:8080"
    
volumes:
  redis_data:

      
